### ISSUE TITLE
Errors :(

### ISSUE THREAD

**Issue by RZRZR** [RZRZR/music-box#2]
Still receiving: 

ledsketch.ino: In function 'void receiveData(int)':
ledsketch:62: error: 'state' cannot be used as a function
ledsketch:63: error: 'led' was not declared in this scope
ledsketch:64: error: 'state' cannot be used as a function
ledsketch:67: error: 'led' was not declared in this scope
ledsketch:68: error: 'state' cannot be used as a function

**Comment by Lily2point0** [comment]
I think I've fixed it but it seems I'm unable to push :S

**Comment by RZRZR** [comment]
I am getting 

ledsketch_doesn_t_yet_work.ino: In function 'void receiveData(int)':
ledsketch_doesn_t_yet_work:62: error: 'int' is not a template
ledsketch_doesn_t_yet_work:62: error: 'PiDataCount' cannot appear in a constant-expression
ledsketch_doesn_t_yet_work:62: error: expected primary-expression before 'int'
ledsketch_doesn_t_yet_work:62: error: expected `;' before 'int'
ledsketch_doesn_t_yet_work:62: error: expected primary-expression before 'int'
ledsketch_doesn_t_yet_work:62: error: expected`)' before 'int'
ledsketch_doesn_t_yet_work:62: error: declaration does not declare anything
ledsketch_doesn_t_yet_work:62: error: name lookup of 'i' changed for new ISO 'for' scoping
ledsketch_doesn_t_yet_work:62: error: using obsolete binding at 'i'
ledsketch_doesn_t_yet_work:62: error: expected `;' before ')' token
ledsketch_doesn_t_yet_work:84: error: expected`}' at end of input
ledsketch_doesn_t_yet_work:84: error: expected `}' at end of input
